apiVersion: compute.gcp.crossplane.io/v1beta1
kind: Subnetwork
metadata:
  name: crossplane-test-subnet
  labels:
     service: vpc
     creation: crossplane
spec:
  forProvider:
    ipCidrRange: '192.168.0.0/21'
    privateIpGoogleAccess: true
    networkSelector:
      matchLabels:
       service: vpc 
       creation: crossplane
    # pick a the closest region to you, although for a tutorial, it won't matter much which
    region: us-east1
  providerConfigRef:
    name: crossplane-provider-gcp


