apiVersion: compute.gcp.crossplane.io/v1beta1
kind: Network
metadata:
  name: crossplane-built-nw
  labels:
     service: vpc
     creation: crossplane
spec:
  forProvider:
    autoCreateSubnetworks: false
    description: 'This is a network built by crossplane'
    routingConfig: 
      routingMode: 'REGIONAL'
  providerConfigRef:
    name: crossplane-provider-gcp
